name: todoapp
description: A project for Manabie's testing

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  cupertino_icons: ^1.0.0
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  provider: ^4.1.2
  get_it: ^4.0.2
  pull_to_refresh: ^1.6.4
  logger: ^0.9.1
  flutter_spinkit: ^4.1.2
  enum_to_string: ^1.0.14
  route_annotation: ^0.2.1
  build_runner: ^1.10.0
  route_generator: ^0.1.5
  pedantic: ^1.9.2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.14.4
  mockito: ^4.1.1
  sqflite_common_ffi:


dependency_overrides:
  analyzer: 0.40.6
  intl: ^0.17.0-nullsafety.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/langs/

  fonts:
    - family: NunitoBlack
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
    - family: NunitoBold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: NunitoExtraBold
      fonts:
        - asset: assets/fonts/Nunito-ExtraBold.ttf
    - family: NunitoExtraLight
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
    - family: NunitoLight
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
    - family: NunitoRegular
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: NunitoSemiBold
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf